### ISSUE TITLE
Simplify `tag` in `Friends` (aka remove `Friends`)?

### ISSUE THREAD

**Issue by stwunsch** [KIT-CMS/ntuple_processor#22]
Could you explain what https://github.com/KIT-CMS/ntuple_processor/blob/master/utils/_booking.py#L53 is doing? Also, we do not use the tags at all, right?

In case I'm right, just remove the `Friend` class and just use the `NTuple` for it. There's no real need to sublcass it again. Then, you can also remove the `NTupleBase` and just use `NTuple` for everything.

**Comment by stwunsch** [comment]
We just agreed that we want an explicit tag of the friend in the `NTuple` constructor or give the `NTuple` a name so that we can still build the chains efficiently. Though move finding the name of the tag to `dataset_from_artusoutput` and no in the `NTuple` constructor.

**Comment by maxgalli** [comment]
Addressed as well in https://github.com/KIT-CMS/ntuple_processor/pull/31
