### ISSUE TITLE
Proposal: Use hashes as tags in names

### ISSUE THREAD

**Issue by stwunsch** [KIT-CMS/ntuple_processor#25]
We could use hashes a tags appended to the names of the results. Each has is unique for each path we go in the computation graphs, which means we can identify results with the same name but different paths. This should then throw a warning.

**Comment by maxgalli** [comment]
Throwing warning if actions have same name addressed in https://github.com/KIT-CMS/ntuple_processor/pull/31

**Comment by stwunsch** [comment]
In #31, are the results overwritten if they have the same name? In case yes, I would say throw an error and not a warning.

**Comment by stwunsch** [comment]
@maxgalli What is the current behaviour? Could you remind me?

**Comment by maxgalli** [comment]
yes I forgot to address this. If they have the same name, a warning is raised and they end up in the root file with the same name but a different ";n" at the end (e.g. ";1", ";2", ecc.)

**Comment by stwunsch** [comment]
ah but that's a cycle, which basically means that you override them. could you raise an error?

**Comment by maxgalli** [comment]
yes sure

**Comment by maxgalli** [comment]
I put it in the same fat PR that you reviewed

**Comment by stwunsch** [comment]
Thanks, perfect!
