### ISSUE TITLE
Add sanity check that each dataframe runs only one event loop

### ISSUE THREAD

**Issue by stwunsch** [KIT-CMS/ntuple_processor#26]
Otherwise throw warning.

**Comment by stwunsch** [comment]
https://root.cern/doc/master/classROOT_1_1RDF_1_1RInterface.html#adfb0562a9f7732c3afb123aefa07e0df

**Comment by maxgalli** [comment]
Addressed in https://github.com/KIT-CMS/ntuple_processor/pulls
