### ISSUE TITLE
Add error handling to variations

### ISSUE THREAD

**Issue by stwunsch** [KIT-CMS/ntuple_processor#35]
I'm missing basic error handling in the variations, e.g., if you want to use `ReplaceCut`, then you should throw an error if the requested cut is not found. Same goes for all other classes.

**Comment by maxgalli** [comment]
should I implement all of them the same way you did here? https://github.com/KIT-CMS/ntuple_processor/pull/34/commits/ac02a4adc03e7d50dea33a84d0f2a32d9ad4a93a

**Comment by stwunsch** [comment]
yes, please. so that it ends up in the logging.

**Comment by maxgalli** [comment]
Implemented in https://github.com/KIT-CMS/ntuple_processor/pull/43
