### ISSUE TITLE
Measure time in each process for the event loop

### ISSUE THREAD

**Issue by stwunsch** [KIT-CMS/ntuple_processor#37]
Put a time measurement in the `_run_multiprocess` function and return the time. this should then be available for the user to see how imbalanced the runs are. also, add a debug message in the `_run_multiprocess` function for that purpose. that would clear up many cases of "bad scaling".

**Comment by maxgalli** [comment]
addressed in https://github.com/KIT-CMS/ntuple_processor/pull/38
